services:
  app:
    build: ./server
    ports:
      - "0.0.0.0:8085:8080"
  postgres:
    image: postgres:16
    container_name: passwords-db
    environment:
      POSTGRES_DB: password_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
